# Generated by Django 2.2.2 on 2019-07-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uZipcode',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
