# Generated by Django 2.2.2 on 2019-07-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='oaddress',
            field=models.CharField(default='', max_length=150),
        ),
    ]
